SevenSpicesWebsite/SevenSpicesWebsite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('items.urls', namespace = 'orders')),
    path('', user_views.home, name = 'home'),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logged-out/', auth_views.LogoutView.as_view(template_name='home.html'), name = 'logout_home'),
#     path('password-reset/',
#          auth_views.PasswordResetView.as_view(
#              template_name='users/password_reset.html'
#          ),
#          name='password_reset'),
#     path('password-reset/done/',
#          auth_views.PasswordResetDoneView.as_view(
#              template_name='users/password_reset_done.html'
#          ),
#          name='password_reset_done'),
#     path('password-reset-confirm/<uidb64>/<token>/',
#          auth_views.PasswordResetConfirmView.as_view(
#              template_name='users/password_reset_confirm.html'
#          ),
#          name='password_reset_confirm'),
#     path('password-reset-complete/',
#          auth_views.PasswordResetCompleteView.as_view(
#              template_name='users/password_reset_complete.html'
#          ),
#          name='password_reset_complete'),
#     path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SevenSpicesWebsite/items/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    # path('new/', views.OrderCreateView.as_view(), name = 'new_order'),
    path('new/', views.menu_items_view, name = 'new_order'),
    path('menu/', views.menu_list_view, name = 'menu_list'),
    path('item-detail/<int:pk>', views.menu_item_detail, name = 'item_detail'),
    # path('my-orders/', views.OrderListView.as_view(), name = 'my_orders'),
    path('order-info/', views.new_order_info, name='order_info'),
    path('add-order-info/', views.add_order_info, name='add_order_info'),
    path('customize/<int:pk>/<str:type>/', views.customize_item, name = 'customize_item'),
    path('add-to-order/<int:pk>/<str:type>/<int:order_item_pk>/', views.add_to_order, name = 'add_to_order'),
    path('delete-item/<int:pk>/', views.delete_item, name='delete_item'),
    path('checkout/', views.checkout, name='checkout'),
    path('my-orders/', views.my_orders, name = 'my_orders'),
    path('order-detail/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail')

]

SevenSpicesWebsite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'items/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'items/new_order_page.css' %}">

    {% if title %}
        <title>Seven Spices - {{ title }}</title>
    {% else %}
        <title>Seven Spices eRestaurant</title>
    {% endif %}

</head>
<body>

  <!-- LEFT CENTERED NAVBAR ACROSS ENTIRE SITE-->
  <!-- <div class="row">
    <div class="col-md-9" style="padding-right:0;">
      <nav class="navbar"style="background-color:white;height:80px;box-shadow: 4px 4px 4px 0 rgba(0, 0, 0, 0.5);" >
          <div class="col-md-2" style="">
            . . .
          </div>
          <div class="col-md-9">
            <div class="navbar-main-content-section">
              <div class="navbar nav">
                {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'orders:order_info' %}">New Order</a>
                  <a class="nav-item nav-link" href="{% url 'orders:my_orders' %}">My Orders</a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                  <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                {% endif %}

                <a class="navbar-brand" href="{% url 'home' %}">Seven Spices</a>

                {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'orders:menu_list' %}">View Menu</a>
                  <a class="nav-item nav-link" href="{% url 'logout_home' %}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'orders:menu_list' %}">View Menu</a>
                  <a class="nav-item nav-link" href="{% url 'orders:order_info' %}">New Order</a>
                {% endif %}
              </div>
            </div>
          </div>
          <div class="col-md-1">

          </div>
      </nav>
    </div>
    <div class="col-md-3" style="background-color:white;height:80px;box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.5);">

    </div>
  </div> -->


  <div class="row">
    <div class="col-md-9" style="padding-right:0;background-color:white;box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.5);">
      <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="height:80px;width:100%;position:relative;z-index:inherit;">
        <div class="col-md-1">
          ...
        </div>

        <div class="col-md-10">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav" style="width:100%">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'orders:order_info' %}" style="color:black;margin:auto;">New Order</a>
                <a class="nav-item nav-link" href="{% url 'orders:my_orders' %}" style="color:black;margin:auto;">My Orders</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}" style="color:black;margin:auto;">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}" style="color:black;margin:auto;">Register</a>
              {% endif %}

              <a class="navbar-brand" href="{% url 'home' %}" style="color:black;margin:auto;">Seven Spices</a>

              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'orders:menu_list' %}" style="color:black;margin:auto;">View Menu</a>
                <a class="nav-item nav-link" href="{% url 'logout_home' %}" style="color:black;margin:auto;">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'orders:menu_list' %}" style="color:black;margin:auto;">View Menu</a>
                <a class="nav-item nav-link" href="{% url 'orders:order_info' %}" style="color:black;margin:auto;">New Order</a>
              {% endif %}
            </div>
          </div>
        </div>

      </nav>
    </div>
    <div class="col-md-3" style="background-color:white;box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.5);">

    </div>
  </div>



  <main role="main" class="">
    <div class="row">
      <div class="col-md-9 col-sm-9" style="padding-right:0;">
        {% block content %}{% endblock %}
      </div>
      <div class="col-md-3 col-sm-3" style="padding-left:0;">
        <div class="content-section" style="
            width: 23%;
            margin-top: 0;
            position: fixed;
            overflow-y: scroll;
            top: 0;
            bottom: 0;
            box-shadow: 0 0 10px 1px gray;
            ">
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" style="border-radius:0;margin-top:5px;text-align:center;" >
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% block sidebar_content %}{% endblock %}
        </div>
      </div>
    </div>
  </main>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <script type="text/javascript">
    // script for fading out messages 1.5s

    // setTimeout(function(){$('.alert').fadeOut();}, 1500);
    // $(window).click(function(){$('.alert').fadeOut();});
    // $('.alert').fadeOut(1500);

  </script>
</body>
</html>

SevenSpicesWebsite/templates/home.html
{% extends 'base.html' %}

{% block content %}

<style media="screen">
  body{
    margin-top:0;
  }
  main{
    padding-right:0;

  }
</style>

<div class="banner-content" style="background-image:linear-gradient(to right, rgb(114,184,95,1), rgb(114,184,95,.3));width:100%;box-shadow: 0 4px 8px 2px rgba(0, 0, 0, 0.5);margin-bottom:2%;">
  <div class="row" style="height:100%;">
    <div class="col-md-7" style="padding-left:20px;height:100%;text-align:left;argin-top:10%;padding:5%;">
      <h4 style="font-weight:600;color:white;">Only Delicious and Fresh Ingredients</h4>
      <h1 style="font-size:50px;font-weight:900;color:white;">Seven Spices</h1>
      <p style="font-weight:450;color:white;">Lorem ipsum dolor sit amet, consectetur aitation ullamco laboris nisi ut dolore eu fugiat nulla pariatur. Excepteur sint pa qui officia deserunt mollit anim id est laborum.</p>
    </div>

    <div class="col-md-5" style="background-color:#f7f7f7;border-top-left-radius:50%;border-bottom-left-radius:50%;text-align:center;align-items:center;box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.5);">
      <!-- border-bottom-right-radius:100%; -->
      <img src="media/general_pics/home_page_2.jpg" style="width:85%;height:80%;border:20px solid white;border-radius:50%;display:inline-block;margin:10%;box-shadow: 0 4px 8px 2px rgba(0, 0, 0, 0.2);transform:rotate(3.5deg)" alt="">
    </div>
  </div>

</div>

<div class="second-banner-content" style="background-image:linear-gradient(to right, #ff9d2f, #ff6126);width:100%;box-shadow: 0 4px 8px 2px rgba(0, 0, 0, 0.5);margin-bottom:5%;">
  <div class="row">
    <div class="col-md-5" style="background-color:#f7f7f7;border-top-right-radius:50%;border-bottom-right-radius:50%;text-align:center;align-items:center;box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);">
      <!-- border-bottom-right-radius:100%; -->
      <img src="media/general_pics/home_page.jpg" style="width:85%;height:80%;border:20px solid white;border-radius:50%;display:inline-block;margin:10%;box-shadow: 0 4px 8px 2px rgba(0, 0, 0, 0.2);" alt="">
    </div>

    <div class="col-md-7" style="padding-left:20px;height:100%;text-align:left;argin-top:10%;padding:5%;">
      <h1 style="font-size:50px;font-weight:900;color:white;">Seven Spices</h1>
      <h4 style="font-weight:600;color:white;">About Us</h4>
      <p style="font-weight:450;color:white;">Lorem ipsum dolor sit amet, consectetur aitation ullamco laboris nisi ut dolore eu fugiat nulla pariatur. Excepteur sint pa qui officia deserunt mollit anim id est laborum.</p>

    </div>
  </div>
</div>

{% endblock %}

{% block sidebar_content %}

<style media="screen">
  .content-section{
    /* background-color:pink; */
  }
</style>

{% endblock %}

SevenSpicesWebsite/templates/home2.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'items/main.css' %}">

    <title>Seven Spices eRestaurant</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-blue fixed-top">
        <div class="container">
            <!-- <a class="navbar-brand mr-4" href="#">Seven Spices</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button> -->
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <!-- {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="#">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="#">Login</a>
                <a class="nav-item nav-link" href="#">Register</a>
              {% endif %}
              <a class="nav-item nav-link" href="#">My Orders</a> -->
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'orders:my_orders' %}"><strong>My Orders</strong></a>
                <a class="nav-item nav-link" href="{% url 'logout_home' %}"><strong>Logout</strong></a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}"><strong>Login</strong></a>
                <a class="nav-item nav-link" href="{% url 'register' %}"><strong>Register</strong></a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <div class="container">
      <h1 align='center' >Welcome to Seven Spices</h1>
      <div class="jumbotron">
        <a class="btn btn-primary btn-large mb-2" href="{% url 'orders:order_info' %}">New Order</a><br>
        <a class="btn btn-success btn-large mb-2" href="{% url 'orders:menu_list' %}">View Menu</a><br>
        <a class="btn btn-info btn-large mb-2" href="#">Contact</a>
      </div>

    </div>
    <!-- <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main> -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>