SevenSpicesWebsite/SevenSpicesWebsite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('items.urls', namespace = 'orders')),
    path('', user_views.home, name = 'home'),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logged-out/', auth_views.LogoutView.as_view(template_name='home.html'), name = 'logout_home'),
#     path('password-reset/',
#          auth_views.PasswordResetView.as_view(
#              template_name='users/password_reset.html'
#          ),
#          name='password_reset'),
#     path('password-reset/done/',
#          auth_views.PasswordResetDoneView.as_view(
#              template_name='users/password_reset_done.html'
#          ),
#          name='password_reset_done'),
#     path('password-reset-confirm/<uidb64>/<token>/',
#          auth_views.PasswordResetConfirmView.as_view(
#              template_name='users/password_reset_confirm.html'
#          ),
#          name='password_reset_confirm'),
#     path('password-reset-complete/',
#          auth_views.PasswordResetCompleteView.as_view(
#              template_name='users/password_reset_complete.html'
#          ),
#          name='password_reset_complete'),
#     path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SevenSpicesWebsite/items/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    # path('new/', views.OrderCreateView.as_view(), name = 'new_order'),
    path('new/', views.menu_items_view, name = 'new_order'),
    path('menu/', views.menu_list_view, name = 'menu_list'),
    path('item-detail/<int:pk>', views.menu_item_detail, name = 'item_detail'),
    # path('my-orders/', views.OrderListView.as_view(), name = 'my_orders'),
    path('order-info/', views.new_order_info, name='order_info'),
    path('add-order-info/', views.add_order_info, name='add_order_info'),
    path('customize/<int:pk>/<str:type>/', views.customize_item, name = 'customize_item'),
    path('add-to-order/<int:pk>/<str:type>/<int:order_item_pk>/', views.add_to_order, name = 'add_to_order'),
    path('delete-item/<int:pk>/', views.delete_item, name='delete_item'),
    path('checkout/', views.checkout, name='checkout'),
    path('my-orders/', views.my_orders, name = 'my_orders'),
    path('order-detail/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail')

]

SevenSpicesWebsite/items/views.py
from django.contrib.auth.models import User
from .models import (Order, MenuItem, Address, OrderItem,
                    Topping, ToppingsCategory, ItemsCategory)
from users.models import Profile
from django.views.generic import CreateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from items.extras import generate_order_id
from django.http import HttpResponseRedirect
from django.contrib import messages



class MenuListView(ListView):
    model = MenuItem
    template_name = 'items/menu_list.html'

def menu_list_view(request):
    item_list = MenuItem.objects.all()

    context = {'item_list': item_list,
                'item_categories':reversed(ItemsCategory.objects.all()),
                'item_categories_side_nav':reversed(ItemsCategory.objects.all())}

    return render(request, 'items/menu_list.html', context)


def menu_item_detail(request, **kwargs):
    item = MenuItem.objects.filter(id=kwargs.get('pk')).first()

    context = {'item':item}

    return render(request, 'items/item_details.html', context)


@login_required()
def new_order_info(request):
    user_profile = get_object_or_404(Profile, user=request.user)
    order, created = Order.objects.get_or_create(customer=user_profile.user, is_ordered=False)
    if created:
        order.ref_code = generate_order_id()
        order.save()
    context = {'order':order}

    return render(request, 'items/order_info.html', context)


@login_required()
def add_order_info(request):
    street_address = request.POST.get("Street-Address")
    appartment_number = request.POST.get("Apartment-Number")
    postal_code = request.POST.get("Postal-Code")
    order_type = request.POST.get("Order-Type")

    user_profile = get_object_or_404(Profile, user=request.user)

    order = get_user_pending_order(request) # change to get_or_create

    address = Address(street_address=street_address,
                      appartment_number=appartment_number,
                      postal_code=postal_code)

    address_duplicate = Address.objects.filter(street_address=street_address,
                                             appartment_number=appartment_number,
                                             postal_code=postal_code).first()

    if not address_duplicate:
        address.save()
        address.orders.add(order)
        address.customers.add(user_profile)
        address.save()
        user_profile.addresses.add(address)
        order.delivered_to_address = address
    else:
        if not user_profile in address_duplicate.customers.all():
            address_duplicate.customers.add(user_profile)
        if not order in address_duplicate.orders.all():
            address_duplicate.orders.add(order)
        address_duplicate.save()
        order.delivered_to_address = address_duplicate

    order.type = order_type
    order.save()

    return redirect(reverse('orders:new_order'))


# item view
@login_required()
def menu_items_view(request):
    item_list = MenuItem.objects.all()
    user_profile = get_object_or_404(Profile, user=request.user)
    current_order, create = Order.objects.get_or_create(customer=user_profile.user, is_ordered=False) #change to get_user_pending_order()

    # update all item prices if they had toppings added to them
    for order_item in current_order.order_items.all():
        order_item.get_item_price()
        order_item.save()
    current_order.get_order_total()
    current_order.save() # maybe unneccessary line

    context = {'item_list': item_list,
                'current_order':current_order,
                'item_categories':reversed(ItemsCategory.objects.all()),
                'item_categories_side_nav':reversed(ItemsCategory.objects.all())}

    return render(request, 'items/order_create.html', context)




# customize item view
@login_required()
def customize_item(request, **kwargs):
    type = kwargs.get('type')

    order_item = 0

    current_order = get_user_pending_order(request)
    if type == 'add':
        item = MenuItem.objects.filter(id=kwargs.get('pk')).first()
    elif type == 'edit':
        order_item = OrderItem.objects.filter(id=kwargs.get('pk')).first()
        item = order_item.item

    topping_categories = []
    for topping in item.toppings.all():
        if not topping.category in topping_categories:
            topping_categories.append(topping.category)

    context = {'current_order':current_order,
                'topping_categories':topping_categories,
                'toppings':item.toppings.all(),
                'item':item,
                'type':type,
                'order_item':order_item}
    # if order_item:
    # context['order_item'] = order_item

    return render(request, 'items/order_create_toppings.html', context)


# after item has been customized with add-ons/toppings, add it to customers current order
@login_required()
def add_to_order(request, **kwargs):

    # if the request is to edit an item
    if kwargs.get('type') == 'edit':
        # retrieve current order
        order = get_user_pending_order(request)

        # retrieve order_item
        order_item = OrderItem.objects.filter(id=kwargs.get('pk')).first()

        # clear all toppings from order_item
        order_item.toppings.clear()

        # clear item from order
        order.order_items.remove(order_item)
        # order.order_items.delete(order_item)

    # if the request is to add an item
    elif kwargs.get('type') == 'add':
        # retrieving user profile
        user_profile = get_object_or_404(Profile, user=request.user)

        # instantiate Order if this first item being added or get order thats
        #   already instantiated
        order, created = Order.objects.get_or_create(customer=user_profile.user, is_ordered=False) # change to get_user_pending_order()

        if created:
            order.ref_code = generate_order_id()
            order.save()

        # retrieve item from all items
        order_item = OrderItem(item=MenuItem.objects.filter(id=kwargs.get('pk')).first())

    order_item.save()

    # retrive all the inputted toppings for the item and adding it to item toppings
    for category in ToppingsCategory.objects.all():
        category_inputs = request.POST.getlist(category.name)
        print(category_inputs)

        if category.type == 'number':
            for i in range(0, len(category_inputs)):
                if category_inputs[i] and int(category_inputs[i]):
                    topping_input = order_item.item.toppings.filter(category=category)[i].name
                    topping = Topping.objects.filter(name=topping_input).first()
                    order_item.toppings.add(topping)
        else:
            for topping_input in category_inputs:
                topping = Topping.objects.filter(name=topping_input).first()
                order_item.toppings.add(topping)

    order_item.save()

    # retrieving quantity of this item
    order_item_quantity = int(request.POST.get('Item-Quantity'))

    # display success messages
    if kwargs.get('type') == 'add':
        if order_item_quantity > 1:
            messages.success(request, f'{order_item_quantity} {order_item}\'s have been added to your order!')
        else:
            messages.success(request, f'{order_item} has been added to your order!')
    else:
        messages.success(request, f'Changes to your {order_item} have been saved!')


    # adding item_quantity amount of items to order
    while(order_item_quantity):
        # creating new instance of order item for each quantity to add to order
        new_item = OrderItem(item=order_item.item, order_item_order=order)
        new_item.save()
        # copying toppings from order_item to new instance of order item
        for topping in order_item.toppings.all():
            new_item.toppings.add(topping)
        order.order_items.add(new_item)
        order.save()
        order_item_quantity -= 1

    # deleting this extra instance of order item from database.
    order_item.delete()

    return redirect(reverse('orders:new_order'))


@login_required()
def delete_item(request, **kwargs):
    order = get_user_pending_order(request)
    item_to_delete = order.order_items.filter(id=kwargs.get('pk')).first()
    order.order_items.remove(item_to_delete)
    order.save()
    return redirect(reverse('orders:new_order'))


@login_required()
def checkout(request):
    current_order = get_user_pending_order(request)
    # ontario_tax_rate = 0.13
    # current_order.total += current_order.total * ontario_tax_rate
    # current_order.save()
    context = {'current_order':current_order}

    return render(request, 'items/checkout.html', context)


@login_required()
def process_payment(request):
    pass


@login_required()
def update_transaction_records(request):
    # add ordered items to the users profile
    pass


@login_required()
def my_orders(request):
    my_user_profile = Profile.objects.filter(user=request.user).first()
    my_orders = Order.objects.filter(customer=my_user_profile.user)
    # my_user = User.objects.filter(username=request.user.username).first()
    # my_orders = my_user.profile.orders.all()
    context = {
                'my_orders': my_orders,
                }

    return render(request, "items/order_list.html", context)


class OrderDetailView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = 'items/order_details.html'


# HELPER FUNCTION


# get the current order that customer is working on
def get_user_pending_order(request):
    user_profile = get_object_or_404(Profile, user=request.user)
    current_order = Order.objects.filter(customer=user_profile.user, is_ordered=False)
    if current_order.exists():
        return current_order[0]
    return 0


# find length of given queryset
def query_set_len(qSet):
    len = 0

SevenSpicesWebsite/items/templates/items/item_details.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<style media="screen">
  body{
    margin-top:0;
  }
</style>

`<div class="container">
  <div class="jumbotron">
    <h1 align='center' >{{item}}</h1>
      <!-- Item description --> <p></p>

  </div>

</div>`

{% endblock %}

SevenSpicesWebsite/items/templates/items/menu_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'items/order_list.css' %}">


<style media="screen">
  body{
    margin-top:0;
  }
</style>

<!-- <div class="container">
  <h1 align='center'>Menu</h1>
  {% for item in menuitem_list %}
    <div class="jumbotron">
      <a href="{% url 'orders:item_detail' pk=item.id %}"><p>{{item.name}}</p></a>
      <p>{{item.price}}</p>
    </div>
  {% endfor %}
</div> -->

<header>
  <h1 style="font-weight:700;">Our Menu</h1>
</header>

<section>
  <div class="order-list-content-section" style="padding-top:5%;background-image: linear-gradient(to right, rgb(114,184,95,1), rgb(114,184,95,.45));margin:5%;margin-top:0;box-shadow: 0 4px 8px 2px rgba(0, 0, 0, 0.5);">
    <!-- <div class="row"> -->

      <!-- <div class="col-md-1 item-category-select" style="padding:0;"> -->

        <!-- <ul class="list-group list-group-flush category-select-ul" style="padding-left:15px;padding-right:15px;">


          <li class="list-group-item list-group-item-light list-group-item-hover onclick-highlight" style="color:#407496;background-color:white;border-right:1px solid #818182;border-left:1px solid #818182;box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2)" onclick="openItems('All'), highlightCategoryText(this)">
            <i class="category-side-display-element">All</i>
          </li>

          {% for category in item_categories_side_nav %}
            <li class="list-group-item list-group-item-hover onclick-highlight" style="color:#aeaeae;border-right:1px solid #818182;border-left:1px solid #818182;box-shadow:0 4px 8px 0 rgba(0, 0, 0, 0.2)" onclick="openItems('{{category}}'), highlightCategoryText(this)">
              {{category}}
            </li>
          {% endfor %}

          <div class="" style="border-bottom:2px solid #818182;border-radius:16px;">

          </div>

        </ul> -->

      <!-- </div> -->

      <div class="item-select" style="text-align:center;padding:10%;padding-top:0;">
        {% for category in item_categories %}
          <div id="{{category}}" class="items" style="margin-bottom:35px;">
            <div class="category-header-name" style="text-align:left;">
              <h3 class="category-display" style="color:white;margin-bottom:25px;">{{category}}</h3>
            </div>

            <div class="row">
            {% for item in item_list %}
              {% if item.category == category %}
                <div class="col-xl-4 col-lg-6 col-md-12 col-sm-12 col-xs-12" style="text-align:center;">
                  <button id="customize-item-modal" style="text-decoration:none;width:350px;height:285px;" type="button" class="btn btn-link add-item" data-toggle="modal" data-target="#exampleModalCenter" value="{{item.id}} {{item.image.url}}" name="{{item}}">
                  {% if item.image %}
                    <div class="polaroid" style="border-radius:8px;">
                      <img src="{{item.image.url}}" alt="" style="width:100%;height:200px;border-top-right-radius:8px;border-top-left-radius:8px;">
                      <div class="topleft item-price">${{item.price}}</div>
                      <div class="polaroid-container" style="text-shadow:1px 2px rgba(0, 0, 0, 0.2);">
                          {{item}}
                      </div>
                    </div>
                  {% endif %}
                  </button>
                </div>
              {% endif %}
            {% endfor %}
            </div>
          </div>
        {% endfor %}
      </div>

      <!-- <div class="col-md-2" style="border-left:1px solid black;">
      </div> -->

    </div>
  <!-- </div> -->
</section>

{% endblock %}

SevenSpicesWebsite/items/templates/items/order_create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'items/Customize_item_iFrame.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'items/new_order_page.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'items/main.css' %}">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


<div class="new-order-container container" style="padding-right:0;margin-top:0;margin-left:0;margin-right:0;">
  <div class="new-order-header" style="">
    <div class="row" style="background-image:linear-gradient(to left, rgb(114,184,95,1), rgb(114,184,95,.3));"> <!-- rgb(226,78,66,1) -->
      <div class="col-md-2" style="background-color:">
        <!-- #11bec4 -->
        <!--  -->
      </div>

      <div class="col-md-10" style="height:100px;border-right:1px solid #818182;px;border-bottom:1px solid #818182;background-color:;border-bottom-right-radius:8px;box-shadow: 0 2px 0 0 rgba(0, 0, 0, 0.2);"> <!-- #11bec4 -->
        <div class="row">
          <div class="col-md-2">

          </div>
          <!-- <div class="col-md-6 new-order-info-header" style="background-color:white;border-left:1px solid #818182;padding-left:125px;padding-right:125px;"> -->
            <!-- <h1 align='center' style="padding-top:25px;padding-bottom:25px;border:1px solid #818182;vertical-align:baseline;box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);border-radius:4px;">Click on item to customize and add to order</h1> -->
          <!-- </div> -->
          <div class="col-md-8" style="padding-top:70px;">
            <div class="">
              <h1 align='center' style="background-image:linear-gradient(#ff9d2f, #ff6126);padding-top:25px;padding-bottom:25px;border:1px solid #818182;vertical-align:baseline;box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);border-radius:12px;color:white;text-shadow:2px 2px 4px rgba(0, 0, 0, 0.75);">customize and add to order</h1>
            </div>
          </div>
          <div class="col-md-2">

          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2" style="height:100px;border-right:1px solid gray;border-bottom:1px solid gray;border-bottom-right-radius:8px;box-shadow:0 4px 8px 0 rgba(0, 0, 0, 0.2);background-image:linear-gradient(to left, rgb(114,184,95,.43), rgb(114,184,95,.3));">

    </div>

    <div class="col-md-2">

    </div>
  </div>

  <div class="row">

    <div class="col-md-2 item-category-select" style="padding:0;">

      <ul class="list-group list-group-flush category-select-ul" style="padding-left:15px;padding-right:15px;">

        <!-- <div class="" style="background-color:#E24E42;height:15px;">

        </div> -->

        <li class="list-group-item list-group-item-light list-group-item-hover onclick-highlight" style="color:#407496;background-color:white;border-right:1px solid #818182;border-left:1px solid #818182;box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2)" onclick="openItems('All'), highlightCategoryText(this)">
          <i class="category-side-display-element">All</i>
        </li>

        {% for category in item_categories_side_nav %}
          <li class="list-group-item list-group-item-hover onclick-highlight" style="color:#aeaeae;border-right:1px solid #818182;border-left:1px solid #818182;box-shadow:0 4px 8px 0 rgba(0, 0, 0, 0.2)" onclick="openItems('{{category}}'), highlightCategoryText(this)">
            {{category}}
          </li>
        {% endfor %}

        <div class="" style="border-bottom:2px solid #818182;border-radius:16px;">

        </div>

      </ul>

    </div>

    <div class="col-md-10 item-select" style="text-align:center;padding:2%;padding-top:0;">
      {% for category in item_categories %}
        <div id="{{category}}" class="items" style="margin-bottom:35px;">
          <div class="category-header-name" style="text-align:left;">
            <h3 class="category-display" style="color:#aeaeae;margin-bottom:25px;">{{category}}</h3>
          </div>

          <div class="row">
          {% for item in item_list %}
            {% if item.category == category %}
              <div class="col-xl-4 col-lg-6 col-md-12 col-sm-12 col-xs-12" style="text-align:center;">
                <button id="customize-item-modal" style="text-decoration:none;width:350px;height:285px;" type="button" class="btn btn-link add-item" data-toggle="modal" data-target="#exampleModalCenter" value="{{item.id}} {{item.image.url}}" name="{{item}}">
                {% if item.image %}
                  <div class="polaroid" style="border-radius:8px;">
                    <img src="{{item.image.url}}" alt="" style="width:100%;height:200px;border-top-right-radius:8px;border-top-left-radius:8px;">
                    <div class="topleft item-price">${{item.price}}</div>
                    <div class="polaroid-container" style="text-shadow:1px 2px rgba(0, 0, 0, 0.2);">
                        {{item}}
                    </div>
                  </div>
                {% endif %}
                </button>
              </div>
            {% endif %}
          {% endfor %}
          </div>
        </div>
      {% endfor %}
    </div>

    <!-- <div class="col-md-2" style="border-left:1px solid black;">
    </div> -->

  </div>

</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <img class="model-header-item-image" src="" alt="" style="width:100%;border-top-right-radius:4px;border-top-left-radius:4px;box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);">
      <div class="modal-image-header" style="width:100%;height:65px;position:absolute;top:0;background-image:linear-gradient(rgb(85,85,85,.6), rgb(85,85,85,0));">
        <div class="customize-item-text-image" style="padding-left:4%;">
          <h3 class="modal-title" id="exampleModalCenterTitle" style="padding-top:10px;color:white;font-size:23px;text-shadow:2px 2px 4px rgba(0, 0, 0, 0.75);">Customize Item</h3>
        </div>
        <div class="close-modal" style="right:5%;">
          <button type="button" class="close" style="padding-top:10px;font-size:33px;color:white;text-shadow:2px 2px 4px rgba(0, 0, 0, 0.75);" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
      <!-- <div class="modal-header">
        hello
      </div> -->
      <div class="modal-body">
        <iframe name="add-item-toppings-iframe" id="add-item-toppings-iframe"
        src=""
        width="465" height="365" frameborder="0">
        </iframe>
      </div>
      <div class="modal-footer" style="box-shadow: 10px 4px 8px 10px rgba(0, 0, 0, 0.2);">
        <input class="btn btn-primary btn-xl btn-block add-to-order-button"
        type="submit"
        value="ADD TO ORDER"
        style="background-color:#e24e42;border:0;">
      </div>
    </div>
  </div>
</div>

{% endblock  %}

{% block sidebar_content %}


  <!-- Side Bar Current Order -->
  <form class="Current-Order-Form" action="{% url 'orders:checkout' %}" method="POST">
    {% csrf_token %}
    <div class="checkout-header">
      <h5 id="subtotal-header" align='center'>Subtotal: ${{current_order.total}}</h5>
      <input id="checkout-button" class="btn btn-primary btn-xl btn-block mb-3" style="background-image:linear-gradient(#ff9d2f, #ff6126);border:0;" type="submit" value="CHECKOUT">
      <h6 align='center'>Click on item to edit</h6>
    </div>

    <p class='text-muted'>
      <ul class="list-group list-group-flush">
        {% for order_item in current_order.order_items.all %}
          <li class="list-group-item list-group-item-light order-item-display">
            <!-- Delete order item -->
            <a class="close" href="{% url 'orders:delete_item' pk=order_item.id %}">
              <span aria-hidden="true">&times;</span>
            </a>

            <!-- Order Item display. Click on order item to edit -->
            <div class="">
              <div class="order-item-edit-button">
                <button id="customize-item-modal" style="text-decoration:none;color:#407496" type="button" class="btn btn-link edit-item" data-toggle="modal" data-target="#exampleModalCenter" value="{{order_item.id}} {{order_item.item.image.url}}" name="{{order_item}}">
                  {{order_item}}
                </button>
              </div>
              <div class="order-item-price-display">
                <p><strong>${{order_item.price}}</strong></p>
              </div>
            </div>

            {% for category in order_item.get_all_topping_categories %}
            <small>
              <!-- <ul> -->
                <!-- <li><strong>{{category}}</strong></li> -->
                <ul class="topping-display-list" style="padding-left:20px;">
                  {% for topping in order_item.toppings.all %}
                    {% if topping.category == category %}
                      <li>{{topping}} {% if topping.price > 0 %} <strong>${{topping.price}} {% endif %}</strong></li>
                    {% endif %}
                  {% endfor %}
                </ul>
              <!-- </ul> -->
            </small>
            {% endfor %}

          </li>

        {% empty %}
        <div class="container">
          <ul class="list-group" >
            <li class="list-group-item list-group-item-light empty-cart-display">
              <h4 align='center' style="margin-bottom: 0px;">Your Cart Is Empty :(</h4>
            </li>
          </ul>
        </div>
        {% endfor %}
      </ul>
    </p>
  </form>


<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<!-- Modal Toggle Script -->
<script type="text/javascript">

  /*
  This script will toggle the modal which includes the iframe for customizing items toppings
  when an item has been selected to add to order or to edit the item that has already
  been added to the order
  */

  var addButtons = $("[id=customize-item-modal]")
  var iFrame = document.getElementById("add-item-toppings-iframe");
  var itemImage = document.querySelector('.model-header-item-image');
  var modalTitle = document.getElementById("exampleModalCenterTitle");

  addButtons.click(function(){
    // the name attribute is the item
    modalTitle.textContent = `Customize your ${this.name}`

    itemImage.setAttribute('src', this.value.split(" ")[1]);

    button = document.querySelector('.add-to-order-button');

    if (this.getAttribute('class') == "btn btn-link add-item"){
      type = 'add'
      button.setAttribute('value', 'ADD TO ORDER')
    }
    else{
      type = 'edit'
      button.setAttribute('value', 'SAVE CHANGES')
    }

    // the value attribute is the item.id
    iFrame.setAttribute('src', `/orders/customize/${this.value.split(" ")[0]}/${type}/`)

  })

</script>


<script type="text/javascript">

  /*
  This script will: once clicked on a category in the left side nav menu, items of that
  category will be displayed and the text of that category on the side nav menu will
  be highlighted until a new category is selected
  */

  function openItems(category){
    var i;
    var x = document.getElementsByClassName("items");

    if(category == 'All'){
      var display = 'block'
    }
    else {
      var display = 'none'
    }
    for (i = 0; i < x.length; i++){
      x[i].style.display = display;
    }

    if(category != 'All')
      document.getElementById(category).style.display = "block";

  }

  function highlightCategoryText(element){

    all_elements = document.querySelectorAll(".list-group-item-hover");

    for(var i = 0; i < all_elements.length; i++){
      all_elements[i].style.color = '#aeaeae'; // light gray
      // all_elements[i].style.boxShadow = ''; // light gray
    }

    element.style.color = '#407496'; //highlighted blue
    // element.style.boxShadow =  "0 0 10px 2px rgba(0, 140, 186, 0.5)";
  }

</script>

<script type="text/javascript">

  button = document.querySelector('.add-to-order-button');

  button.addEventListener('click', function(){
    window.frames['add-item-toppings-iframe'].document.querySelector('.Add-Toppings-Form').submit();
  })

</script>

{% endblock %}